### ISSUE TITLE
Requirement for custom rfcdiff

### ISSUE THREAD

**Issue by cinemast** [lvc/pkgdiff#22]
Hi Andrey!

I currently packaged rfcdiff for Debian and was wondering to which extend your custom rfcdiff script is necessary for pkgdiff to work properly? 

Could your changes to it, be merged into upstream rfcdiff?

Greetings
Peter

**Comment by cinemast** [comment]
Also, would it work to use the upstream version of rfcdiff? 

https://tools.ietf.org/tools/rfcdiff/index

**Comment by cinemast** [comment]
Just as an FYI: Do you know about the tool diffoscope?
https://diffoscope.org/
It apparently does almost the same as pkgdiff. It also lists your tool as alternative.

**Comment by aponomarenko** [comment]
Hi,

Most of the changes to the rfcdiff tool are too specific to be included by upstream.

I see only one chunk of patch that can be submitted to upstream (in order to make creation of the tmp directory more reliable):

    @@ -102,11 +117,10 @@
    -export workdir="/tmp/$basename-$$"
    +export workdir=`mktemp -d -t rfcdiff.XXXXXXXX`

Thank you.

**Comment by aponomarenko** [comment]
Thanks for the link to the diffoscope project! Nice tool but seems that it's too young to be a valuable alternative for the Pkgdiff. Pkgdiff is used at https://fossies.org/diffs/ and I'll continue development and support of the Pkgdiff tool for a long time. I'm surprised that Debian uses diffoscope at https://reproducible.debian.net/ instead of Pkgdiff.

**Comment by cinemast** [comment]
Alright, thanks for the info.

Great to hear that you plan to keep pkgdiff supported well. I will package it as is and deal with the partly duplicate functionality of rfcdiff.

Sorry, I don't know the reasons for diffoscope over pkgdiff. 

Greetings
Peter
